# Generated by Django 3.1.5 on 2021-01-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0002_auto_20210126_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group', to='plans.proceduregroup')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dosage1', models.CharField(blank=True, max_length=150)),
                ('dosage2', models.CharField(blank=True, max_length=150)),
                ('dosage3', models.CharField(blank=True, max_length=150)),
                ('dosage4', models.CharField(blank=True, max_length=150)),
                ('drug1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug1', to='drugs.drug')),
                ('drug2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug2', to='drugs.drug')),
                ('drug3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug3', to='drugs.drug')),
                ('drug4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug4', to='drugs.drug')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group', to='plans.prescriptiongroup')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='CycleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.SmallIntegerField(default=21)),
                ('p1_start', models.SmallIntegerField(default=1, verbose_name='Start day')),
                ('p1_end', models.SmallIntegerField(default=21, verbose_name='End day')),
                ('p2_start', models.SmallIntegerField(default=1, verbose_name='Start day')),
                ('p2_end', models.SmallIntegerField(default=21, verbose_name='End day')),
                ('p3_start', models.SmallIntegerField(default=1, verbose_name='Start day')),
                ('p3_end', models.SmallIntegerField(default=21, verbose_name='End day')),
                ('p4_start', models.SmallIntegerField(default=1, verbose_name='Start day')),
                ('p4_end', models.SmallIntegerField(default=21, verbose_name='End day')),
                ('proc1_cycleday', models.SmallIntegerField(default=0, verbose_name='Cycle day')),
                ('proc2_cycleday', models.SmallIntegerField(default=0, verbose_name='Cycle day')),
                ('proc3_cycleday', models.SmallIntegerField(default=0, verbose_name='Cycle day')),
                ('proc4_cycleday', models.SmallIntegerField(default=0, verbose_name='Cycle day')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='p1', to='plans.prescription', verbose_name='Prescription 1')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='p2', to='plans.prescription', verbose_name='Prescription 2')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='p3', to='plans.prescription', verbose_name='Prescription 3')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='p4', to='plans.prescription', verbose_name='Prescription 4')),
                ('proc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proc1', to='plans.procedure', verbose_name='Procedure 1')),
                ('proc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proc2', to='plans.procedure', verbose_name='Procedure 2')),
                ('proc3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proc3', to='plans.procedure', verbose_name='Procedure 3')),
                ('proc4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proc4', to='plans.procedure', verbose_name='Procedure 4')),
            ],
        ),
    ]
