# Generated by Django 3.1.5 on 2021-01-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210126_2316'),
        ('plans', '0002_auto_20210127_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='drug',
        ),
        migrations.AddField(
            model_name='procedure',
            name='dosage_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='procedure',
            name='dosage_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='procedure',
            name='dosage_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='procedure',
            name='drug_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_1', to='drugs.drug', verbose_name='Drug 1'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='drug_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_2', to='drugs.drug', verbose_name='Drug 2'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='drug_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_3', to='drugs.drug', verbose_name='Drug 3'),
        ),
    ]
