# Generated by Django 3.1.5 on 2021-01-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210126_2316'),
        ('plans', '0003_auto_20210127_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['description', 'order']},
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='procedure',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='dosage_1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='dosage_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='dosage_3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='drug_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_1', to='drugs.drug'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='drug_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_2', to='drugs.drug'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='drug_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_3', to='drugs.drug'),
        ),
    ]
