# Generated by Django 3.1.5 on 2021-01-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20210127_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['description', 'order']},
        ),
    ]
