# Generated by Django 3.1.5 on 2021-01-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20210127_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['group', 'title']},
        ),
    ]
