# Generated by Django 3.1.5 on 2021-01-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20210127_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['group']},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['order']},
        ),
    ]
