# Generated by Django 3.1.5 on 2021-01-25 23:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Drug classes',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countries', multiselectfield.db.fields.MultiSelectField(choices=[('GBR', 'United Kingdom'), ('ITA', 'Italy'), ('NLD', 'Netherlands'), ('USA', 'United States'), ('ESP', 'Spain'), ('CAN', 'Canada'), ('GER', 'GER'), ('AUS', 'Australia')], max_length=255)),
                ('active_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='active_ingredient', to='drugs.activeingredient')),
                ('drug_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_class', to='drugs.drugclass')),
            ],
        ),
    ]
