# Generated by Django 3.1.5 on 2021-01-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='active_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_ingredient', to='drugs.activeingredient'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_class', to='drugs.drugclass'),
        ),
    ]
