# Generated by Django 3.1.5 on 2021-01-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210126_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugclass',
            options={'ordering': ['name'], 'verbose_name_plural': 'Drug classes'},
        ),
    ]
