# Generated by Django 3.1.5 on 2021-01-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('GBR', 'United Kingdom'), ('ITA', 'Italy'), ('NLD', 'Netherlands'), ('USA', 'USA'), ('ESP', 'Spain'), ('CAN', 'Canada'), ('GER', 'Germany'), ('AUS', 'Australia')], max_length=30)),
                ('order', models.SmallIntegerField(default=0)),
                ('active_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='active_ingredient', to='calc.activeingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('dosage_regimen', models.CharField(default='', max_length=150)),
                ('order', models.SmallIntegerField(default=0)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug', to='calc.drug')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group', to='calc.druggroup')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescription1_start', models.DateField(blank=True, null=True)),
                ('prescription1_end', models.DateField(blank=True, null=True)),
                ('prescription2_start', models.DateField(blank=True, null=True)),
                ('prescription2_end', models.DateField(blank=True, null=True)),
                ('prescription3_start', models.DateField(blank=True, null=True)),
                ('prescription3_end', models.DateField(blank=True, null=True)),
                ('prescription4_start', models.DateField(blank=True, null=True)),
                ('prescription4_end', models.DateField(blank=True, null=True)),
                ('prescription5_start', models.DateField(blank=True, null=True)),
                ('prescription5_end', models.DateField(blank=True, null=True)),
                ('cycle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cycle_type', to='calc.cycletype')),
                ('prescription1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescription1', to='calc.prescription')),
                ('prescription2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescription2', to='calc.prescription')),
                ('prescription3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescription3', to='calc.prescription')),
                ('prescription4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescription4', to='calc.prescription')),
                ('prescription5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescription5', to='calc.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='drug_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_class', to='calc.drugclass'),
        ),
    ]
