# Generated by Django 3.1.5 on 2021-01-24 21:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrugGroup',
            new_name='PrescriptionGroup',
        ),
        migrations.AlterField(
            model_name='drug',
            name='country',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GBR', 'United Kingdom'), ('ITA', 'Italy'), ('NLD', 'Netherlands'), ('USA', 'USA'), ('ESP', 'Spain'), ('CAN', 'Canada'), ('GER', 'Germany'), ('AUS', 'Australia')], max_length=255),
        ),
    ]
