# Generated by Django 3.1.5 on 2021-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210124_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
