# Generated by Django 3.1.5 on 2021-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20210124_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
