# Generated by Django 3.1.5 on 2021-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20210124_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptiongroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='prescriptiongroup',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
